"""rename phone_mac to device_id in Employee and PunchRecord tables

Revision ID: 007
Revises: 006
Create Date: 2026-01-26 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers
revision = '007'
down_revision = '006'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Add new device_id columns
    op.add_column('Employee', sa.Column('device_id', sa.String(length=100), nullable=True))
    op.add_column('PunchRecord', sa.Column('device_id', sa.String(length=100), nullable=True))
    
    # 2. Copy data from phone_mac to device_id
    connection = op.get_bind()
    connection.execute("UPDATE Employee SET device_id = phone_mac WHERE phone_mac IS NOT NULL")
    connection.execute("UPDATE PunchRecord SET device_id = phone_mac WHERE phone_mac IS NOT NULL")
    
    # 3. Drop old phone_mac columns
    op.drop_column('Employee', 'phone_mac')
    op.drop_column('PunchRecord', 'phone_mac')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Add back phone_mac columns
    op.add_column('PunchRecord', sa.Column('phone_mac', sa.String(length=20), nullable=True))
    op.add_column('Employee', sa.Column('phone_mac', sa.String(length=20), nullable=True))
    
    # 2. Copy data from device_id to phone_mac
    connection = op.get_bind()
    connection.execute("UPDATE Employee SET phone_mac = device_id WHERE device_id IS NOT NULL")
    connection.execute("UPDATE PunchRecord SET phone_mac = device_id WHERE device_id IS NOT NULL")
    
    # 3. Drop device_id columns
    op.drop_column('PunchRecord', 'device_id')
    op.drop_column('Employee', 'device_id')
    # ### end Alembic commands ###