"""使用内置 sqlite3 初始化核心表

Revision ID: b43ce6da1d5b
Revises: 03df05bcf73d
Create Date: 2026-01-12 16:31:13.455983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b43ce6da1d5b'
down_revision = '03df05bcf73d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CostAllocation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='自增主键'),
    sa.Column('cost_name', sa.String(length=100), nullable=False, comment='费用名称（如物料损耗、房租）'),
    sa.Column('cost_amount', sa.Numeric(precision=12, scale=2), nullable=False, comment='费用金额（元）'),
    sa.Column('cost_type', sa.String(length=20), nullable=False, comment='费用类型（一次性/每月/每季/每年）'),
    sa.Column('apply_scope', sa.String(length=20), nullable=False, comment='适用范围（全局/单个订单）'),
    sa.Column('order_id', sa.Integer(), nullable=True, comment='关联订单ID（仅单个订单费用填写）'),
    sa.Column('effective_date', sa.Date(), nullable=False, comment='生效日期'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注（费用用途）'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Employee',
    sa.Column('id', sa.UUID(), nullable=False, comment='UUID主键'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='员工姓名'),
    sa.Column('emp_id', sa.String(length=20), nullable=False, comment='工号（唯一标识）'),
    sa.Column('dept', sa.String(length=50), nullable=True, comment='部门'),
    sa.Column('phone_mac', sa.String(length=20), nullable=False, comment='手机MAC地址（唯一）'),
    sa.Column('inner_ip', sa.String(length=20), nullable=False, comment='内网IP（固定）'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('emp_id'),
    sa.UniqueConstraint('inner_ip'),
    sa.UniqueConstraint('phone_mac')
    )
    op.create_table('OrderList',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='自增主键（序号）'),
    sa.Column('is_new', sa.Integer(), nullable=True, comment='新旧（1=新/0=旧）'),
    sa.Column('area', sa.String(length=50), nullable=True, comment='地区'),
    sa.Column('customer_name', sa.String(length=100), nullable=True, comment='客户名称'),
    sa.Column('customer_type', sa.String(length=20), nullable=True, comment='经销商/终端'),
    sa.Column('order_time', sa.Date(), nullable=True, comment='下单时间'),
    sa.Column('ship_time', sa.Date(), nullable=True, comment='出货时间'),
    sa.Column('ship_country', sa.String(length=50), nullable=True, comment='发运国家'),
    sa.Column('contract_no', sa.String(length=50), nullable=True, comment='合同编号'),
    sa.Column('order_no', sa.String(length=50), nullable=True, comment='订单编号'),
    sa.Column('machine_no', sa.String(length=50), nullable=True, comment='包装机单号'),
    sa.Column('machine_name', sa.String(length=100), nullable=True, comment='设备名称'),
    sa.Column('machine_model', sa.String(length=50), nullable=True, comment='机型'),
    sa.Column('machine_count', sa.Integer(), nullable=True, comment='主机数量'),
    sa.Column('unit', sa.String(length=10), nullable=True, comment='单位'),
    sa.Column('contract_amount', sa.Numeric(precision=12, scale=2), nullable=True, comment='合同人民币金额（元）'),
    sa.Column('deposit', sa.Numeric(precision=12, scale=2), nullable=True, comment='定金（元）'),
    sa.Column('balance', sa.Numeric(precision=12, scale=2), nullable=True, comment='尾款（元）'),
    sa.Column('tax_refund_amount', sa.Numeric(precision=12, scale=2), nullable=True, comment='退税后总金额（元）'),
    sa.Column('currency_amount', sa.Numeric(precision=12, scale=2), nullable=True, comment='美金/RMB金额'),
    sa.Column('payment_received', sa.Numeric(precision=12, scale=2), nullable=True, comment='回款（元）'),
    sa.Column('direct_cost', sa.Numeric(precision=12, scale=2), nullable=True, comment='直接成本（元）'),
    sa.Column('commission', sa.Numeric(precision=12, scale=2), nullable=True, comment='佣金（元）'),
    sa.Column('allocated_cost', sa.Numeric(precision=12, scale=2), nullable=True, comment='摊分费用（元）'),
    sa.Column('custom_income', sa.Numeric(precision=12, scale=2), nullable=True, comment='自定义增收费用（元）'),
    sa.Column('custom_expense', sa.Numeric(precision=12, scale=2), nullable=True, comment='自定义减支费用（元）'),
    sa.Column('gross_profit', sa.Numeric(precision=12, scale=2), nullable=True, comment='毛利（元）'),
    sa.Column('net_profit', sa.Numeric(precision=12, scale=2), nullable=True, comment='净利（元）'),
    sa.Column('pay_type', sa.String(length=20), nullable=True, comment='T/T OR LC'),
    sa.Column('latest_ship_date', sa.Date(), nullable=True, comment='最迟装运期'),
    sa.Column('expected_delivery', sa.Date(), nullable=True, comment='预计交期'),
    sa.Column('order_dept', sa.String(length=50), nullable=True, comment='下单部门'),
    sa.Column('check_requirement', sa.Text(), nullable=True, comment='验收要求'),
    sa.Column('attachment_imgs', sa.String(length=500), nullable=True, comment='验收图片路径（多图逗号分隔）'),
    sa.Column('attachment_videos', sa.String(length=500), nullable=True, comment='验收视频路径（多视频逗号分隔）'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('PunchRecord',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='自增主键'),
    sa.Column('emp_id', sa.String(length=20), nullable=False, comment='关联员工工号'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='员工姓名'),
    sa.Column('punch_type', sa.String(length=20), nullable=False, comment='打卡类型（上班/下班）'),
    sa.Column('punch_time', sa.DateTime(), nullable=True, comment='打卡时间'),
    sa.Column('inner_ip', sa.String(length=20), nullable=True, comment='打卡设备IP'),
    sa.Column('phone_mac', sa.String(length=20), nullable=True, comment='打卡设备MAC地址'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('TotpUser',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='自增主键'),
    sa.Column('emp_id', sa.String(length=20), nullable=False, comment='关联员工工号'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='员工姓名'),
    sa.Column('totp_secret', sa.String(length=16), nullable=False, comment='TOTP密钥（唯一）'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('emp_id')
    )
    op.drop_table('order_list')
    op.drop_table('punch_record')
    op.drop_table('cost_allocation')
    op.drop_table('totp_user')
    op.drop_table('employee')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee',
    sa.Column('id', sa.NUMERIC(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('emp_id', sa.VARCHAR(length=20), nullable=False),
    sa.Column('dept', sa.VARCHAR(length=50), nullable=True),
    sa.Column('phone_mac', sa.VARCHAR(length=20), nullable=False),
    sa.Column('inner_ip', sa.VARCHAR(length=20), nullable=False),
    sa.Column('create_time', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('emp_id'),
    sa.UniqueConstraint('inner_ip'),
    sa.UniqueConstraint('phone_mac')
    )
    op.create_table('totp_user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('emp_id', sa.VARCHAR(length=20), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('totp_secret', sa.VARCHAR(length=16), nullable=False),
    sa.Column('create_time', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('emp_id')
    )
    op.create_table('cost_allocation',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('cost_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('cost_amount', sa.NUMERIC(precision=12, scale=2), nullable=False),
    sa.Column('cost_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('apply_scope', sa.VARCHAR(length=20), nullable=False),
    sa.Column('order_id', sa.INTEGER(), nullable=True),
    sa.Column('effective_date', sa.DATE(), nullable=False),
    sa.Column('remark', sa.TEXT(), nullable=True),
    sa.Column('create_time', sa.DATETIME(), nullable=True),
    sa.Column('update_time', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('punch_record',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('emp_id', sa.VARCHAR(length=20), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('punch_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('punch_time', sa.DATETIME(), nullable=True),
    sa.Column('inner_ip', sa.VARCHAR(length=20), nullable=True),
    sa.Column('phone_mac', sa.VARCHAR(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_list',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('is_new', sa.INTEGER(), nullable=True),
    sa.Column('area', sa.VARCHAR(length=50), nullable=True),
    sa.Column('customer_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('customer_type', sa.VARCHAR(length=20), nullable=True),
    sa.Column('order_time', sa.DATE(), nullable=True),
    sa.Column('ship_time', sa.DATE(), nullable=True),
    sa.Column('ship_country', sa.VARCHAR(length=50), nullable=True),
    sa.Column('contract_no', sa.VARCHAR(length=50), nullable=True),
    sa.Column('order_no', sa.VARCHAR(length=50), nullable=True),
    sa.Column('machine_no', sa.VARCHAR(length=50), nullable=True),
    sa.Column('machine_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('machine_model', sa.VARCHAR(length=50), nullable=True),
    sa.Column('machine_count', sa.INTEGER(), nullable=True),
    sa.Column('unit', sa.VARCHAR(length=10), nullable=True),
    sa.Column('contract_amount', sa.NUMERIC(precision=12, scale=2), nullable=True),
    sa.Column('deposit', sa.NUMERIC(precision=12, scale=2), nullable=True),
    sa.Column('balance', sa.NUMERIC(precision=12, scale=2), nullable=True),
    sa.Column('tax_refund_amount', sa.NUMERIC(precision=12, scale=2), nullable=True),
    sa.Column('currency_amount', sa.NUMERIC(precision=12, scale=2), nullable=True),
    sa.Column('payment_received', sa.NUMERIC(precision=12, scale=2), nullable=True),
    sa.Column('direct_cost', sa.NUMERIC(precision=12, scale=2), nullable=True),
    sa.Column('commission', sa.NUMERIC(precision=12, scale=2), nullable=True),
    sa.Column('allocated_cost', sa.NUMERIC(precision=12, scale=2), nullable=True),
    sa.Column('custom_income', sa.NUMERIC(precision=12, scale=2), nullable=True),
    sa.Column('custom_expense', sa.NUMERIC(precision=12, scale=2), nullable=True),
    sa.Column('gross_profit', sa.NUMERIC(precision=12, scale=2), nullable=True),
    sa.Column('net_profit', sa.NUMERIC(precision=12, scale=2), nullable=True),
    sa.Column('pay_type', sa.VARCHAR(length=20), nullable=True),
    sa.Column('latest_ship_date', sa.DATE(), nullable=True),
    sa.Column('expected_delivery', sa.DATE(), nullable=True),
    sa.Column('order_dept', sa.VARCHAR(length=50), nullable=True),
    sa.Column('check_requirement', sa.TEXT(), nullable=True),
    sa.Column('attachment_imgs', sa.VARCHAR(length=500), nullable=True),
    sa.Column('attachment_videos', sa.VARCHAR(length=500), nullable=True),
    sa.Column('create_time', sa.DATETIME(), nullable=True),
    sa.Column('update_time', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('TotpUser')
    op.drop_table('PunchRecord')
    op.drop_table('OrderList')
    op.drop_table('Employee')
    op.drop_table('CostAllocation')
    # ### end Alembic commands ###
