"""简化版权限常量定义"""

# 全体共有权限的路由
ROUTE_DISPLAY_FILE_MANAGE = "display_file_manage"  # 文件展示
ROUTE_PHOTO_MANAGE = "photo_manage"                # 照片管理
ROUTE_PUNCH_MANAGE = "punch_manage"                # 打卡
ROUTE_UPLOAD_MANAGE = "upload_manage"              # 文件上传模块
ROUTE_VIDEO_MANAGE = "video_manage"                # 视频管理
ROUTE_MACHINE_LIST = "machine_list"                # 设备列表
ROUTE_ATTENDANCE_MANAGE = "attendance_manage"      # 考勤管理

# 销售角色权限
ROUTE_INQUIRY_MANAGE = "inquiry_manage"            # 询盘管理
ROUTE_ORDER_MANAGE = "order_manage"                # 订单管理
ROUTE_ORDER_STATUS_MANAGE = "order_status_manage"  # 订单状态
ROUTE_QUOTATION_MANAGE = "quotation_manage"        # 报价管理

# 管理员独有权限
ROUTE_EXPENSE_MANAGE = "expense_manage"            # 费用管理
ROUTE_LOG_MANAGE = "log_manage"                    # 日志管理
ROUTE_MACHINE_MANAGE = "machine_manage"            # 设备管理
ROUTE_USER_MANAGE = "user_manage"                  # 员工信息/管理
ROUTE_PERMISSION_MANAGE = "permission_manage"      # 权限管理（如果保留的话）
ROUTE_ORDER_RECORD_MANAGE = "order_record_manage"  # 订单记录管理

# 业务员权限
ROUTE_CUSTOMER_MANAGE = "customer_manage"           # 客户信息管理

# 为了兼容性，添加旧的命名方式
ROUTE_DISPLAY_FILE = ROUTE_DISPLAY_FILE_MANAGE
ROUTE_PHOTO = ROUTE_PHOTO_MANAGE
ROUTE_PUNCH = ROUTE_PUNCH_MANAGE
ROUTE_UPLOAD = ROUTE_UPLOAD_MANAGE
ROUTE_VIDEO = ROUTE_VIDEO_MANAGE
ROUTE_INQUIRY = ROUTE_INQUIRY_MANAGE
ROUTE_ORDER = ROUTE_ORDER_MANAGE
ROUTE_ORDER_STATUS = ROUTE_ORDER_STATUS_MANAGE
ROUTE_EXPENSE = ROUTE_EXPENSE_MANAGE
ROUTE_LOG = ROUTE_LOG_MANAGE
ROUTE_MACHINE = ROUTE_MACHINE_MANAGE
ROUTE_USER = ROUTE_USER_MANAGE
ROUTE_PERMISSION = ROUTE_PERMISSION_MANAGE
ROUTE_ATTENDANCE = ROUTE_ATTENDANCE_MANAGE  # 考勤管理
ROUTE_QUOTATION = ROUTE_QUOTATION_MANAGE  # 报价管理

# 所有路由列表
ALL_ROUTES = [
    ROUTE_DISPLAY_FILE_MANAGE,
    ROUTE_PHOTO_MANAGE,
    ROUTE_PUNCH_MANAGE,
    ROUTE_UPLOAD_MANAGE,
    ROUTE_VIDEO_MANAGE,
    ROUTE_INQUIRY_MANAGE,
    ROUTE_ORDER_MANAGE,
    ROUTE_ORDER_STATUS_MANAGE,
    ROUTE_EXPENSE_MANAGE,
    ROUTE_LOG_MANAGE,
    ROUTE_MACHINE_MANAGE,
    ROUTE_MACHINE_LIST,
    ROUTE_USER_MANAGE,
    ROUTE_PERMISSION_MANAGE,
    ROUTE_ATTENDANCE_MANAGE,
    ROUTE_QUOTATION_MANAGE,
    ROUTE_ORDER_RECORD_MANAGE,
    ROUTE_CUSTOMER_MANAGE
]